### PR TITLE
Add support for covers (open/close)

### PR DESCRIPTION
**Pull request by pergolafabio**
Intital PR for opening closing covers

### CODE REVIEW

**Comment by RogerSelwyn** [comment]
I've substantially rewritten this (MQTT open didn't work) and added support for stop service and passing of position/tilt position.

**Comment by pergolafabio** [comment]
Aha, cool, let me try tomorrow, seems my Velux have cover position, never used it :-)

**Comment by RogerSelwyn** [comment]
https://github.com/RogerSelwyn/mqtt_discoverystream_ha/releases/tag/v0.10.8

**Comment by pergolafabio** [comment]
Do you have think script domain can work too?

**Comment by RogerSelwyn** [comment]
No, what is supported is shown here - https://www.home-assistant.io/integrations/mqtt/

**Comment by pergolafabio** [comment]
Too bad :-)

**Pull request merged**
