### PR TITLE
Fix topic prefix validation

### PR DESCRIPTION
**Pull request by miguelangel-nubla**
Had a issue where the entities were working but could not be controlled, this was the root cause.

### CODE REVIEW

**Comment by RogerSelwyn** [comment]
The integration works fine in my environment, without the slash, and I can control entities across instances no problem. So I'll need to review this more.

What type of entity are you trying to control?

**Comment by RogerSelwyn** [comment]
Though it is interesting that I have that code in Publisher.py. Sorry been buried in something else, so have to get my head back into this.

**Comment by RogerSelwyn** [comment]
Though I can see the problem, so I guess it doesn't work....

**Comment by miguelangel-nubla** [comment]
I had the problem with a light, a switch and a cover.
The `cmd_t` topic in `<prefix>/light/<entity_name>/config` was missing the first `/`. `stat_t` and `avty_t` were fine.
```
{
  "uniq_id": "mqtt_light.light_entity_id",
  "obj_id": "light_entity_id",
  "stat_t": "topicprefix/light/light_entity_id/state",
  "avty_t": "topicprefix/light/light_entity_id/availability",
  "name": "light_entity_id",
  "cmd_t": "topicprefixlight/light_entity_id/set_light",
  "schema": "JSON",
  "effect": true,
  "color_mode": true,
...
```

I could also fix it by adding the `/` to the end of the base topic in the configuration:
```
mqtt_discoverystream:
  base_topic: topicprefix/
...
```
It has been working until recently no problem, could not find the change to blame for this.

**Comment by RogerSelwyn** [comment]
I’ve done code “improvement” recently, so that probably messed it up.

**Comment by RogerSelwyn** [comment]
0.11.01 should include your fix.

**Pull request merged**
